baseURL: "https://pearson.onl"
languageCode: "en-us"
title: "Jack Pearson"
menu:
  main:
  - name: home
    url: /
    weight: -120
  - name: projects
    url: /projects/
    weight: -110
  - name: about me
    url: /about-me/
    weight: -100

